services:
  - type: web
    name: calendar-assistant-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_API_KEY
        sync: false
      - fromGroup: calendar-assistant-secrets 